# site properties and page defaults
title: Data Driven PSE @ GT ChBE
subtitle: Boukouvala Research Lab Website
logo-text: true
description: Find out recent news from the Data-Driven Process Systems Engineering Lab at Georgia Tech School of Chemical & Biomolecular Engineering. 
header: images/blurry_network.jpg
footer: images/blurry_network.jpg

# site social media and other links
links:
  email: fani.boukouvala@chbe.gatech.edu
  orcid: 0000-0002-0584-1517
  github: https://github.com/DDPSE


### jekyll settings

# front matter defaults
defaults:
  # all markdown files
  - scope:
      path: ""
    values:
      layout: default
  # markdown files in /_members
  - scope:
      type: "members"
    values:
      layout: member
  # markdown files in /_posts
  - scope:
      type: "posts"
    values:
      layout: post

collections:
  # generate page for each member
  members:
    output: true
  # generate page for each post
  posts:
    output: true

# jekyll plugins
plugins:
  - jekyll-spaceship
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-feed
  - jekyll-last-modified-at

# code block syntax highlighting
highlighter: rouge

# jekyll theme
theme: null

# sass settings
sass:
  sass_dir: _styles

# force jekyll to include certain files/folders
include:
  - _styles
  - _scripts

# force jekyll to exclude certain files/folders
exclude:
  - README.md
  - LICENSE.md
  - CITATION.cff
